/**:
    ros__parameters:
        ## Device settings, provide one of the following:
        ##  - scan_for devices = 
        ##          true:   the driver ignores port and baudrate settings, scans for devices on all ports and selects the first found
        ##          false: = Requires correct port and baudrate both to be specified
        scan_for_devices: true
        port: "/dev/ttyUSB0" # port name, e.g. '/dev/ttyUSB0'
        baudrate: 921600 # non-necessary for some devices

        ## Connect only to specific device_id:
        ##  device_id = '077007EF' (uppercase hex string), returns with error if the device with ID is not found on the ports
        ##  device_id = "" Null string disables this check
        device_id: "" # Null String ("") by default, else uppercase hex string, e.g. '077007EF'

        # Enable logging. Requires name of the file to be specified.
        enable_logging: false
        ## Log file (optional), placed in ~/.ros/ otherwise use absolute path
        log_file: log.mtb

        publisher_queue_size: 5

        # TF transform frame_id (default: imu_link), you may want to change it if you use multiple devices
        frame_id: "imu_link"

        # Message publishers
        pub_imu: true
        pub_quaternion: true
        pub_mag: true
        pub_angular_velocity: true
        pub_acceleration: true
        pub_free_acceleration: true
        pub_dq: true
        pub_dv: true
        pub_sampletime: true
        pub_temperature: true
        pub_pressure: true
        pub_gnss: true
        pub_twist: true
        pub_transform: true
        pub_positionLLA: true
        pub_velocity: true

        ## Sensor standard deviation [x,y,z] (optional)
        ## This value is used to override the covariance matrix in sensor_msgs/Imu and
        ## sensor_msgs/MagneticField messages.
        ## Important: Make sure the values provided are in decimal points, or else might give error in execution
        linear_acceleration_stddev: [0.0, 0.0, 0.0] # [m/s^2]
        angular_velocity_stddev: [0.0, 0.0, 0.0] # [rad/s]
        orientation_stddev: [0.0, 0.0, 0.0] # [rad]
        magnetic_field_stddev: [0.0, 0.0, 0.0] # [Tesla]


        ## Internal device configuration (optional)
        ## These values (if specified) will be applied to the sensor device on startup
        # Configure a new device baudrate
        config_baudrate: 921600
        rtcm_baudrate: 921600

        reset_heading: false
        reset_inclination: false

        # Configure the location ID
        # Can be used to identify Motion Tracker by a number instead of its Device ID. This can be particularly useful
        #   when a fixed setup with multiple interchangeable MT’s is used.
        #TODO(location-id): MTi documentation specifies maximum range of 0-255, however, the driver actually allows
        #   for setting a 16-bit value (actual range 0-65535).
        location_id: 0

        # Apply the host machine current UTC time to the device.
        # This can be set manually here or acquired from GNSS if supported.
        apply_current_utc_time: true

        # Configure the sensor to rotate its output using:
        alignment_local_quat: [1.0, 0.0, 0.0, 0.0] # (identity)
        alignment_sensor_quat: [1.0, 0.0, 0.0, 0.0] # (identity)

        # Configure the GNSS Lever arm. This is the length/position of the antenna with respect to the center of the sensor.
        # It is a 3-vector: x,y,z. Units are in meters.
        # Check the device manual or MTi GUI application to see if this is supported on your device.
        gnss_lever_arm: [0.0, 0.0, 0.0]

        # Configure the initial LLA position for local magnetic declination and gravity estimation.
        # This can be set manually here or acquired from GNSS if supported.
        initial_position_lla: [49.2289, 16.5732, 287.93]

        # Configure the filter profile - check the log output or MTi GUI application to see available profiles on your device.
        onboard_filter_profile: "General_RTK"

        # Configure the GNSS platform setting.
        # See the device manual or MTi GUI application for supported settings on your device.
        # For all API available data identifiers see the `xsgnssplatform.h` file.
        gnss_platform: "Portable"

        # Configure the device output data with DATA_TYPE|DATA_FORMAT|FREQUENCY
        # You can provide these in any order (ex. DATA_FORMAT|FREQUENCY|DATA_TYPE),
        #   however all three fields must always be specified.
        # To disable config modification and keep the currently applied settings, set the first configuration line as an empty string.
        # Valid values are:
        #   DATA_TYPE -> see the device manual or MTi GUI application for supported data types on your device
        #   DATA_FORMAT -> Float (default), Fp1220, Fp1632, Double
        #   FREQUENCY -> see the device manual or MTi GUI application for supported frequencies on your device,
        #       0xFFFF (or 65535) specifies the maximum available on device
        # For all API available data identifiers see the `xsdataidentifier.h` file.
        # Some data types don't support different formats, in which case the default 'Float' option must be set.
        # If you don't see your configured data output, try setting the type to Float and
        #   check the manual or MTi GUI application for valid combinations on your device.
        output_configuration:
            - ""
            - "Temperature|Float|400"
            - "PacketCounter|Float|0xFFFF"
            - "GnssAge|Float|0xFFFF"
            - "SampleTimeFine|Float|0xFFFF"
            - "Quaternion|Float|400"
            - "BaroPressure|Float|100"
            - "DeltaV|Float|400"
            - "Acceleration|Float|400"
            - "FreeAcceleration|Float|400"
            - "AltitudeEllipsoid|Float|400"
            - "LatLon|Float|400"
            - "GnssPvtData|Float|4"
            - "GnssSatInfo|Float|4"
            - "GnssPvtPulse|Float|4"
            - "RateOfTurn|Float|400"
            - "DeltaQ|Float|400"
            - "MagneticField|Float|100"
            - "VelocityXYZ|Float|400"
            - "StatusWord|Float|400"

        # Configure the device option flags.
        # This will always set only the specified flags and unset all others.
        # To disable modification and keep the currently applied flags, set the first configuration line as an empty string.
        # For all API available flags see the `xsdeviceoptionflag.h` file.
        # Not all devices can support all flags, please see the device manual or MTi GUI application for supported flags on your device.
        option_flags:
            - ""
#            - "None"
            - "EnableOrientationSmoother"
            - "EnableInrunCompassCalibration"
            - "EnablePositionVelocitySmoother"
            - "EnableContinuousZRU"
